# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
# ğŸŒˆ STARSHIP CONFIG BY NABIL TZY
# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

format = """
[î»¾](fg:#DE5D09) [î•](fg:#00FF9C)[$username](bold bright-cyan) [on](bold white) [$hostname](bold bright-yellow)[ îº§ ](fg:#FFFFFF) | [î—¾](bright-cyan) [$directory](bold bright-green) \
$git_branch $python $nodejs $rust $c
[ó±©](bold white) """

add_newline = true

# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
# USERNAME & HOSTNAME
# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
[username]
show_always = true
style_user = "italic bright-cyan"
format = " NabilTzy"

[hostname]
ssh_only = false
style = "italic bright-yellow"
format = "$hostname"

# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
# DIRECTORY
# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
[directory]
truncation_length = 3
truncate_to_repo = false
style = " bright-green"
read_only = " ğŸ”’"
format = "($path)($style)"

# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
# GIT
# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
[git_branch]
symbol = "ï˜ "
style = " bright-yellow"
format = "on [$symbol$branch]($style) "

[git_status]
style = " bright-red"
format = "([$all_status$ahead_behind]($style)) "

# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
# LANGUAGES
# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
[python]
symbol = "ğŸ "
style = " bright-yellow"
format = "via [$symbol v$version]($style) "

[nodejs]
symbol = "îœ˜ "
style = " bright-green"
format = "via [$symbol v$version]($style) "

[rust]
symbol = "ğŸ¦€ "
style = " bright-red"
format = "via [$symbol v$version]($style) "

[c]
symbol = "î˜ "
style = " bright-blue"
format = "via [$symbol v$version]($style) "

# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
# CMD DURATION (selalu tampil)
# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
[cmd_duration]
min_time = 0
style = "bold bright-cyan"
format = "took [$duration]($style)"
show_milliseconds = true

